# Generated by Django 6.0.5 on 2026-05-25 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='members.user_profile'),
            preserve_default=False,
        ),
    ]
