# Generated by Django 6.0.5 on 2026-05-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_user_user_profile_transaction_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_profile',
        ),
    ]
