# Generated by Django 6.0.5 on 2026-06-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_user_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
